name: code_of_federal_regulations
description: A representation of Code of Federal Regulations (https://www.govinfo.gov/app/collection/cfr).
version: 0.0.1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  xml: ^6.1.0

  # TODO(security): replace since current package is uploaded by unverified author
  # original files are not organized as a package, disallowed to be fetched
  #    git:
  #      url: https://github.com/google/diff-match-patch.git
  #      path: dart
  #      ref: master
  diff_match_patch: ^0.4.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0